_target_: srnet.models.sr_net_module.SRNetModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: srnet.models.components.sr_dense_net.DenseNet
  input_channels: 3
  scale_factor: 4
  num_dense_blocks: 20
  num_layers: 6
  channels: 64 # needs to be divisible by scale_factor**2
  growth_rate: 32
  kernel_size: 3
  padding: 1
  b_norm: false

# compile model for faster training with pytorch 2.0
compile: false
